name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/your-project
            git pull origin main
            npm run build
            systemctl restart your-service